<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f1eb"><title>Tools — JXHQ</title><meta name="description" content="Kleine, privacyvriendelijke browsertools voor developers en nieuwsgierige mensen."><link rel="canonical" href="https://jxhq.net/tools/"><script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script><link rel="stylesheet" href="/assets/site.css"></head><body>
<main class="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-8 sm:py-12"><header class="mb-14 flex items-center justify-between gap-5"><a class="inline-flex items-center gap-3" href="/"><span class="grid size-10 place-items-center bg-[#ff3b3b] font-black text-white">JX</span><span><strong class="block leading-none">JXHQ</strong><small class="text-[#777c7c]">tools</small></span></a><div class="flex items-center gap-5"><a href="/" class="hidden text-sm font-bold sm:block" data-tool-i18n="backHome">← Terug naar JXHQ</a><div class="flex border border-[#cfcac1] bg-white p-1 text-xs font-black"><button class="px-2.5 py-1.5" data-lang="nl">NL</button><button class="px-2.5 py-1.5" data-lang="en">EN</button></div></div></header>
<section class="mb-14 grid gap-7 border-b border-[#cfcac1] pb-12 sm:grid-cols-12 sm:items-end"><div class="sm:col-span-8"><p class="mb-4 text-xs font-black uppercase tracking-[.16em] text-[#ff3b3b]" data-tool-i18n="toolbox">Gereedschapskist</p><h1 class="text-5xl font-black leading-[.95] tracking-[-.055em] sm:text-7xl"><span data-tool-i18n="heading">Handige tools</span><span class="text-[#ff3b3b]">.</span></h1></div><p class="text-[#686d6d] sm:col-span-4" data-tool-i18n="intro">Snel, eenvoudig en meestal volledig in je browser. Geen account. Geen onzin.</p></section>
<?php $tools=[
['whois','WHO','Domain lookup','Domeingegevens, registratiedatums en nameservers via RDAP.'],
['password-generator','✦','Password generator','Sterke, cryptografisch willekeurige wachtwoorden.'],
['uuid-generator','ID','UUID generator','Genereer één of meer willekeurige UUID v4-identifiers.'],
['json-formatter','{ }','JSON formatter','Formatteer, valideer en verklein JSON lokaal.'],
['qr-generator','QR','QR-code generator','Maak een downloadbare QR-code voor tekst of een link.'],
['jwt-decoder','JWT','JWT decoder','Bekijk headers, claims en verloopdatum van een JWT.'],
['diff-checker','±','Diff checker','Vergelijk twee teksten regel voor regel.'],
['color-converter','●','Color converter','Converteer kleuren tussen HEX, RGB en HSL.'],
['works-on-my-machine','✓','Works on my machine','Genereer overtuigend bewijs dat je build ergens heeft gewerkt.']]; ?>
<section class="grid gap-4 sm:grid-cols-2" aria-label="Tools"><?php foreach($tools as $i=>$tool): ?><a href="/tools/<?= $tool[0] ?>/" class="card-link group flex min-h-56 flex-col justify-between border border-[#d6d2ca] <?= $i===0?'bg-[#111313] text-white':'bg-white' ?> p-6"><div class="flex justify-between"><span class="font-mono text-sm <?= $i===0?'text-[#ff5b5b]':'text-[#ff3b3b]' ?>"><?= $tool[1] ?></span><span>→</span></div><div><h2 class="text-2xl font-black tracking-[-.035em]" data-tool-name="<?= $tool[0] ?>"><?= $tool[2] ?></h2><p class="mt-3 text-sm leading-relaxed <?= $i===0?'text-white/60':'text-[#686d6d]' ?>" data-tool-desc="<?= $tool[0] ?>"><?= $tool[3] ?></p></div></a><?php endforeach; ?></section>
<footer class="mt-16 flex flex-wrap justify-between gap-3 border-t border-[#cfcac1] pt-5 text-xs text-[#777c7c]"><span>© <span id="year"></span> JXHQ</span><span data-tool-i18n="footer">Kleine tools. Verdacht weinig trackers.</span></footer></main><script src="/assets/site.js" defer></script><script src="/assets/tools.js" defer></script><script src="/assets/works-on-my-machine.js" defer></script></body></html>
