<?php
$slug=preg_replace('/[^a-z-]/','',$_GET['tool']??'');
$tools=[
'whois'=>['WHO','Domain lookup','Domeingegevens opzoeken via openbare RDAP-registers.'],
'password-generator'=>['✦','Password generator','Maak sterke wachtwoorden zonder dat ze je browser verlaten.'],
'uuid-generator'=>['ID','UUID generator','Genereer cryptografisch willekeurige UUID v4-identifiers.'],
'json-formatter'=>['{ }','JSON formatter','Formatteer, valideer of verklein JSON lokaal.'],
'qr-generator'=>['QR','QR-code generator','Zet tekst of een link om in een downloadbare QR-code.'],
'jwt-decoder'=>['JWT','JWT decoder','Inspecteer de inhoud en verloopdatum van een JWT lokaal.'],
'diff-checker'=>['±','Diff checker','Vergelijk twee stukken tekst regel voor regel.'],
'color-converter'=>['●','Color converter','Converteer HEX, RGB en HSL zonder hoofdrekenen.']];
if(!isset($tools[$slug])){http_response_code(404);require dirname(__DIR__).'/404.php';exit;}$tool=$tools[$slug];
function textarea(string $id,string $placeholder):void{echo '<textarea id="'.$id.'" class="tool-input min-h-52 font-mono text-sm" placeholder="'.$placeholder.'"></textarea>';}
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f1eb"><title><?= htmlspecialchars($tool[1]) ?> — JXHQ Tools</title><meta name="description" content="<?= htmlspecialchars($tool[2]) ?>"><script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script><?php if($slug==='qr-generator'): ?><script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script><?php endif; ?><link rel="stylesheet" href="/assets/site.css"></head>
<body data-tool="<?= $slug ?>"><main class="mx-auto min-h-screen max-w-3xl px-5 py-8 sm:px-8 sm:py-12"><header class="mb-12 flex items-center justify-between gap-5"><a class="inline-flex items-center gap-3" href="/tools/"><span class="grid size-10 place-items-center bg-[#ff3b3b] font-black text-white">JX</span><span><strong class="block leading-none">JXHQ</strong><small class="text-[#777c7c]">tools / <?= htmlspecialchars($slug) ?></small></span></a><div class="flex border border-[#cfcac1] bg-white p-1 text-xs font-black"><button class="px-2.5 py-1.5" data-lang="nl">NL</button><button class="px-2.5 py-1.5" data-lang="en">EN</button></div></header>
<section class="mb-8 border-b border-[#cfcac1] pb-8"><a href="/tools/" class="mb-7 inline-block text-sm font-bold" data-tool-i18n="backTools">← Alle tools</a><div class="flex items-start gap-5"><span class="grid min-h-12 min-w-12 place-items-center bg-[#111313] px-2 font-mono text-sm font-black text-white"><?= $tool[0] ?></span><div><h1 class="text-4xl font-black tracking-[-.045em] sm:text-5xl" data-tool-title><?= htmlspecialchars($tool[1]) ?></h1><p class="mt-3 text-[#686d6d]" data-tool-description><?= htmlspecialchars($tool[2]) ?></p></div></div></section>
<section class="border border-[#d6d2ca] bg-white p-5 sm:p-7"><div id="tool-message" class="mb-5 hidden border-l-3 border-[#ff3b3b] bg-[#fff3f1] p-3 text-sm" role="status"></div>
<?php if($slug==='whois'): ?><form id="whois-form" class="flex flex-col gap-3 sm:flex-row"><input id="domain" class="tool-input flex-1" placeholder="example.com" maxlength="253" required><button class="tool-button" type="submit" data-tool-i18n="lookup">Opzoeken</button></form><div id="whois-result" class="mt-6 hidden"></div>
<?php elseif($slug==='password-generator'): ?><div class="grid gap-5"><div><label class="mb-2 block text-sm font-bold"><span data-tool-i18n="length">Lengte</span>: <span id="length-value">20</span></label><input id="password-length" class="w-full accent-[#ff3b3b]" type="range" min="8" max="64" value="20"></div><div class="grid grid-cols-2 gap-3 text-sm"><label><input id="use-symbols" type="checkbox" checked class="accent-[#ff3b3b]"> <span data-tool-i18n="symbols">Symbolen</span></label><label><input id="use-numbers" type="checkbox" checked class="accent-[#ff3b3b]"> <span data-tool-i18n="numbers">Cijfers</span></label><label><input id="use-uppercase" type="checkbox" checked class="accent-[#ff3b3b]"> <span data-tool-i18n="uppercase">Hoofdletters</span></label><label><input id="avoid-ambiguous" type="checkbox" class="accent-[#ff3b3b]"> <span data-tool-i18n="ambiguous">Vermijd 0/O/l/I</span></label></div><div class="flex gap-3"><input id="password-output" class="tool-input font-mono" readonly><button id="copy-output" class="tool-button" type="button" data-tool-i18n="copy">Kopieer</button></div><button id="generate-password" class="tool-button" type="button" data-tool-i18n="generate">Nieuw wachtwoord</button></div>
<?php elseif($slug==='uuid-generator'): ?><div class="flex gap-3"><input id="uuid-count" class="tool-input max-w-28" type="number" min="1" max="100" value="5"><button id="generate-uuid" class="tool-button" type="button" data-tool-i18n="generate">Genereren</button><button id="copy-output" class="tool-button" type="button" data-tool-i18n="copy">Kopieer</button></div><textarea id="uuid-output" class="tool-input mt-4 min-h-52 font-mono text-sm" readonly></textarea>
<?php elseif($slug==='json-formatter'): ?><?php textarea('json-input','{"hello":"world"}'); ?><div class="mt-3 flex flex-wrap gap-3"><button id="format-json" class="tool-button" data-tool-i18n="format">Formatteren</button><button id="minify-json" class="tool-button" data-tool-i18n="minify">Verkleinen</button><button id="copy-output" class="tool-button" data-tool-i18n="copy">Kopieer</button></div>
<?php elseif($slug==='qr-generator'): ?><input id="qr-input" class="tool-input" placeholder="https://jxhq.net"><div class="mt-3 flex gap-3"><button id="generate-qr" class="tool-button" data-tool-i18n="generate">Genereren</button><button id="download-qr" class="tool-button" data-tool-i18n="download">Download</button></div><div id="qr-output" class="mt-6 flex min-h-48 items-center justify-center border border-dashed border-[#cfcac1] p-5"></div>
<?php elseif($slug==='jwt-decoder'): ?><?php textarea('jwt-input','eyJhbGciOi...'); ?><button id="decode-jwt" class="tool-button mt-3" data-tool-i18n="decode">Decoderen</button><div id="jwt-output" class="mt-5 grid gap-4"></div>
<?php elseif($slug==='diff-checker'): ?><div class="grid gap-4 sm:grid-cols-2"><?php textarea('diff-left','Oude tekst');textarea('diff-right','Nieuwe tekst'); ?></div><button id="compare-diff" class="tool-button mt-3" data-tool-i18n="compare">Vergelijken</button><pre id="diff-output" class="mt-5 overflow-auto whitespace-pre-wrap border border-[#d6d2ca] bg-[#f8f7f3] p-4 text-sm"></pre>
<?php elseif($slug==='color-converter'): ?><div class="grid gap-5 sm:grid-cols-[9rem_1fr]"><input id="color-picker" type="color" value="#ff3b3b" class="h-32 w-full cursor-pointer border-0 bg-transparent"><div class="grid gap-3"><label class="text-sm font-bold">HEX<input id="hex-output" class="tool-input mt-1 font-mono" value="#FF3B3B"></label><label class="text-sm font-bold">RGB<input id="rgb-output" class="tool-input mt-1 font-mono" readonly></label><label class="text-sm font-bold">HSL<input id="hsl-output" class="tool-input mt-1 font-mono" readonly></label></div></div><?php endif; ?>
</section><p class="mt-5 text-xs text-[#777c7c]" data-tool-i18n="privacy">Privacy note: invoer blijft in je browser, behalve openbare domeinopzoekingen.</p><footer class="mt-12 flex justify-between border-t border-[#cfcac1] pt-5 text-xs text-[#777c7c]"><span>JXHQ Tools</span><span data-tool-i18n="coffee">Werkt op JavaScript en koffie.</span></footer></main><script src="/assets/site.js" defer></script><script src="/assets/tools.js" defer></script></body></html>
